export const regionLabel={'georgia': 'Georgia',
  'florida': 'Florida',
  'california': 'California',
  'minnesota': 'Minnesota'}

export const channelLabel={'catalog': 'Catalog',
  'liqwarehouse': 'Liquidation Warehouse',
  'outlets': 'Outlets',
  'stores': 'Stores',
  'warehouse': 'Warehouse',
  'web': 'e-Commerce',
  'wholesale': 'Wholesale'}
export const storeLabel={'S001': 'str1',
  'S002': 'str2',
  'S003': 'str3',
  'S004': 'str4',
  'S005': 'str5',
  'S006': 'str6',
  'S007': 'str7',
  'S008': 'str8',
  'S009': 'str9',
  'S010': 'str10',
  'S011': 'str11',
  'S012': 'str12',
  'S013': 'str13',
  'S014': 'str14',
  'S015': 'str15',
  'S016': 'str16',
  'S017': 'str17',
  'S018': 'str18',
  'S019': 'str19',
  'S020': 'str20',
  'S021': 'str21',
  'S022': 'str22',
  'S023': 'str23',
  'S024': 'str24',
  'S025': 'str25',
  'S026': 'str26',
  'S027': 'str27',
  'S028': 'str28',
  'S029': 'str29',
  'S030': 'str30',
  'S031': 'str31',
  'S032': 'str32',
  'S033': 'str33',
  'S034': 'str34',
  'S035': 'str35',
  'S036': 'str36',
  'S037': 'str37',
  'S038': 'str38',
  'S039': 'str39',
  'S040': 'str40',
  'S041': 'str41',
  'S042': 'str42',
  'S043': 'str43',
  'S044': 'str44',
  'S045': 'str45',
  'S046': 'str46',
  'S047': 'str47',
  'S048': 'str48',
  'S049': 'str49',
  'S050': 'str50',
  'S051': 'str51',
  'S052': 'str52',
  'S053': 'str53',
  'S054': 'str54',
  'S055': 'str55',
  'S056': 'str56',
  'S057': 'str57',
  'S058': 'str58',
  'S059': 'str59',
  'S060': 'str60',
  'S061': 'str61',
  'S062': 'str62',
  'S063': 'str63',
  'S064': 'str64',
  'S065': 'str65',
  'S066': 'str66',
  'S067': 'str67',
  'S068': 'str68',
  'S069': 'str69',
  'S070': 'str70',
  'S071': 'str71',
  'S072': 'str72',
  'S073': 'str73',
  'S074': 'str74',
  'S075': 'str75',
  'S076': 'str76',
  'S077': 'str77',
  'S078': 'str78',
  'S079': 'str79',
  'S080': 'str80'}
  export const itemLabel={'b1c4': 'Booties',
  'b2c4': 'Rain boots',
  's1c4': 'Wedge sandals',
  's2c4': 'Dress sandals',
  'a1c4': 'Hiking shoes',
  'a2c4': 'Running shoes',
  'd9c7': 'Casual',
  'd4w7': 'Wear to Work',
  'd5w6': 'Wedding Party',
  't1p6': 'Polos',
  'a7c5': 'Cycling shoes',
  'a9r1': 'Running shoes',
  'b5c9': 'Chelsea ',
  't7p5': 'Polos',
  't9w4': 'Woven shirts',
  'j1j7': 'Jackets',
  'j5c7': 'Coat',
  'p7c2': 'Casual',
  'a7l2': 'Legging ',
  'd8s1': 'Special Occasion',
  's9d4': 'Dress sandals',
  'b7r2': 'Rain boots',
  'h7b3': 'Beanie ',
  'p2c0': 'Casual',
  'h0b3': 'Beanie ',
  'n1n4': 'Neckties',
  'b3r0': 'Rain boots',
  'f9f4': 'Foundation  ',
  'f9b0': 'Blush',
  'e9m1': 'Mascara',
  'm0w7': 'Warm & Spicy',
  'w7f0': 'Floral',
  'a3a7': 'Aromatherapy',
  'a9b4': 'Bath gifts',
  'v8h1': 'Herbals',
  'v4m6': 'Minerals',
  'm8p1': 'Poultry ',
  'm8s4': 'Seafood',
  'f4t2': 'Tropical Fruits',
  'f2m9': 'Mixed Vegetables',
  'g5s9': 'Short-cut extruded pasta',
  'g9r6': 'Ribbon-cut pasta',
  'c4g9': 'Granola',
  'c6o1': 'Oatmeal',
  's4l9': 'Liquids',
  's6p1': 'Powders',
  'f1l7': 'Liquids',
  'f1s8': 'Sheets',
  'l2p9': 'Powders',
  'f5f9': 'Freezer Bags',
  'f1p7': 'Plastic Wrap',
  't5b9': 'Bath Tissues',
  'u4a1': 'Android OS',
  'u2a7': 'Apple iOS',
  'r2a3': 'Android OS',
  'c1c2': 'Car Chargers',
  'c1u4': 'USB Chargers',
  'c4s2': 'Screen Protectors',
  's6c4': 'Curved',
  's4f7': 'Flat',
  'd2f6': 'Flat',
  'h5w2': 'Wireless and Bluetooth Headphones',
  'g7n6': 'New',
  'g5r9': 'Refurbished',
  'a6n2': 'New',
  'i6n1': 'New',
  't3n5': 'New',
  'k1w1': 'Wireless',
  'k2w5': 'Wired',
  'u5g5': '4GB',
  'w9n3': 'New',
  'w4n1': 'New',
  'b8s7': 'Shoulder bags',
  'b4b3': 'Backpack',
  'q7n1': 'New',
  'q5n6': 'New',
  'd9n2': 'New',
  'd2r7': 'Refurbished',
  'X': 'Black Cases'}
  export const itemTypeLabel={'b251': 'Boots',
  's264': 'Sandals',
  'a348': 'Athletic',
  'd321': 'Dresses',
  't547': 'Tops&Tees',
  'a245': 'Athletic',
  'b597': 'Boots',
  't479': 'Tops & T-Shirts',
  'j247': 'Jackets & Outerwear',
  'p698': 'Pants',
  'a547': 'Activewear',
  'd147': 'Dresses',
  's745': 'Sandals',
  'b214': 'Boots',
  'h879': 'Hats & Caps',
  'p512': 'Pants',
  'h012': 'Hats & Caps',
  'n628': 'Neckties &Bow Tie',
  'b149': 'Boots',
  'f530': 'Face Makeup',
  'e510': 'Eyes Makeup',
  'm017': "Men's fragrances",
  'w589': "Women's fragrances",
  'a321': 'Aromatherapy & Relaxation',
  'v017': 'Vitamins ',
  'm954': 'Meat ',
  'f698': 'Fruits &vegetables',
  'g021': 'Gluten-Free',
  'c574': 'Cereals',
  's587': 'Stain Removers',
  'f632': 'Fabric Softeners',
  'l357': 'Laundry Detergents',
  'f523': 'Food Storage Bags & Containers',
  't102': 'Toilet Paper',
  'u650': 'Unlocked Phones',
  'r450': 'Refurbished Phones',
  'c201': 'Chargers',
  'c301': 'Cases&Protectors',
  's506': 'Smart Tvs',
  'd201': '3D Tvs',
  'h664': 'Headphones',
  'g547': 'Gaming Desktops',
  'a698': 'All-In-One Desktops',
  'i971': '2-in-1',
  't620': 'Touchscreen Laptop',
  'k570': 'Keyboards, Mice & Joysticks',
  'u658': 'USB Flash Drives',
  'w214': 'Web Cameras',
  'w963': 'Waterproof Cameras',
  'b547': 'Bags & Cases',
  'q657': 'Quad Core',
  'q367': 'Quad Core',
  'd104': 'Dual Core',
  'c541': 'Cases & Bags'}
export const   subclassLabel={'ws2515': 'Shoes',
  'wc4215': 'Clothing',
  'ms2515': 'Shoes',
  'mc4215': 'Clothing',
  'gc3254': 'Clothing',
  'gs9581': 'Shoes',
  'ga9542': 'Accessories',
  'bc6547': 'Clothing',
  'ba1024': 'Accessories',
  'bs5470': 'Shoes',
  'bm547': 'Makeup',
  'bf632': 'Fragrances',
  'hm258': 'Massagers & Spa',
  'hv247': 'Vitamins & Supplements',
  'fp658': 'Produce',
  'fp987': 'Pasta',
  'fb159': 'Breakfast & Cereal',
  'hl147': 'Laundry',
  'hp54': 'Paper & Plastic',
  'cc66': 'Cell Phones',
  'ca31': 'Accessories',
  'tt54': 'TV',
  'ta21': 'Accessories',
  'cd65': 'Desktop Computers',
  'cl54': 'Laptops',
  'cc21': 'Computer Accessories',
  'cc88': 'Cameras',
  'ca87': 'Accessories',
  'ii98': 'iPads',
  'iw32': 'Windows Tablets',
  'ia17': 'Accessories'}
  export const classLabel={'w14': 'Women',
  'm20': 'Men',
  'g67': 'Girls',
  'b12': 'Boys',
  'b21': 'Beauty',
  'h47': 'Health',
  'f85': 'Food',
  'h22': 'Household',
  'c28': 'Cell Phones & Accessories',
  't47': 'Television & Accessories',
  'c64': 'Computers',
  'c72': 'Cameras & Accessories',
  'i36': 'iPad & Tablets'}
  export const departmentLabel={'csj14': 'Clothing/Shoes&Jewelry',
  'hb325': 'Health &beauty',
  'fh489': 'Food &household',
  'ec809': 'Electronics & Computers'}
  export const divisionLabel={'fshon': 'fashion', 'grocery': 'grocery', 'hardlines': 'hardlines'}
  export const companyLabel={'retailer': 'Retailer X'}
  const createReverseMapping = (labels) => {
    return Object.fromEntries(
      Object.entries(labels).map(([key, value]) => [value, key])
    );
  };
  export const skuLabel={'bc54': 'Cole Haan Abbot Ankle Booties',
  'bm23': "MUK LUKS Women's Sydney Rainboots",
  'sw32': "Momo Women's Frieda Slingback Wedge",
  'so64': 'Open Toe Chunky High Heel Ankle Strap Sandals',
  'ac21': "Columbia Women's Dakota Drifter Trail Shoe",
  'aa02': "Avia Women's Breathe Cross-Training Shoe",
  'dv21': "VIISHOW Women's Long Sleeve Casual Loose T-Shirt Dress",
  'do98': "Olrain Women's Classic Slim Fit Sleeveless Midi Dress Belted",
  'de65': 'Ever Pretty Sleeveless V-Neck Semi-Formal Maxi Dress',
  'tz26': 'Zeagoo Womens Short Sleeves Solid Polo Top Pique T-Shirt',
  'as54': "Skechers Sport Men's Afterburn Memory-Foam Lace-up Sneaker",
  'as65': "Skechers Sport Men's Energy Afterburn Lace-Up Sneaker",
  'as61': 'Salomon Mens SPEEDCROSS 4, BLACK/METALLIC',
  'bd96': "Donald J Pliner Men's Enrico Chelsea Boot",
  'tc47': "Chaps Men's Solid Polo",
  'tg25': "George Young Men's Short Sleeve Polo with Scotchgard",
  'tb78': "Burnside Men's Victor Woven Shirt",
  'jw32': "Walls Men's Insulated Duck Hooded Jacket",
  'ju58': 'UF Vintage N-3B Parka ',
  'pg54': "George Big Men's Pleat Front Pant",
  'ap98': "PUMA Girls' Active Legging Capri",
  'dp98': 'Princess Party Rose Flower Lace Ruffled Layered Tutu Skirt Dress',
  'dh56': 'High Low Black Flower Girl Dress',
  'sn54': 'Nova Utopia Toddler Little Girls Low Medium Heel Dress Sandal Shoes',
  'bo87': 'Oakiwear Kids Rubber Rain Boots',
  'hf45': 'Funky Junque’s CC Girls Cable Knit Beanie',
  'pc01': 'Solid Color Casual Pants Pure Cotton ',
  'hk24': 'Koloa Surf Co. Original Soft & Cozy Beanies',
  'nb12': 'Boys Mixed Pattern Pre-Tied Elastic Fashion Necktie',
  'bh58': "Hatley Boys' Classic Printed Rain Boots",
  'bk52': 'Kidorable Blue Space Hero Natural Rubber Rain Boots',
  'fm30': 'Maybelline New York Fit Me Powder',
  'fr41': 'Rimmel Stay Matte Pressed Powder',
  'bm70': 'Milani Powder Blush',
  'el69': "L'Oreal Paris Voluminous Original Mascara",
  'mp14': 'Polo Blue by Ralph Lauren',
  'wb48': 'Bodycology Sweet Seduction Fragrance Mist',
  'aa96': 'Aura Cacia Essential Oil Lavender',
  'ap15': 'Plant Therapy Essential Oil Starter Set 100% Pure',
  'vs14': 'Spring Valley Natural Noni Dietary Supplement Softgels',
  'vv20': 'Viviscal Hair Growth Program Extra Strength Dietary Supplement',
  'mt98': 'Tyson Premium Chunk White Chicken Breast',
  'mt44': 'Trio Chicken Gravy Mix 22.6 oz. Bag',
  'mg12': 'Geisha Tiny Shrimp',
  'mz11': "Zatarain's Crawfish, Shrimp & Crab Boil",
  'fs65': 'sweet passion fruit',
  'fa44': 'avocado',
  'fp96': 'pineapple',
  'fo03': 'Organic Cranberry Walnut Salad',
  'gc41': 'Cannelloni',
  'gl77': 'Lasagne',
  'ck47': 'KIND Healthy Grains Granola Clusters, Peanut Butter Whole Grain',
  'cq65': 'Quaker Instant Oatmeal, Variety Value Pack, Breakfast Cereal',
  'ss56': 'Shout Triple-Acting Laundry Stain Remover, 60.0 FL OZ',
  'so98': 'OxiClean Chlorine Free Laundry Stain Remover Refill, 56 Oz',
  'so14': 'OxiClean Versatile Stain Remover Powder, 5lb',
  'fd58': 'Downy® Ultra April Fresh® Fabric Conditioner 103 fl. oz. Plastic Jug',
  'fd23': 'Downy Dryer Sheets, April Fresh, 200 Sheets',
  'la54': 'Ariel Powder Laundry Detergent Original Scent, 141 ounces, 28 Loads',
  'fg53': 'Great Value Double Zipper Freezer Bags, Quart, 75 Ct',
  'fg60': "Glad Press'n Seal Wrap, 140 Sq Ft",
  'ts50': 'Scott 1000 Sheets Per Roll Bathroom Tissue, Toilet Paper, 12 Rolls',
  'us65': 'Samsung Galaxy S5 Mini G800A 16GB Unlocked GSM 4G LTE Android Phone - Black',
  'ua12': 'Apple iPhone 4S 32GB Unlocked GSM Phone w/ Siri & iCloud - Black ',
  'rs687': 'Samsung Galaxy S5 G900A 16GB w/ 16MP Camera - Black (Certified Refurbished)',
  'cs620': 'Samsung Adaptive Fast Charging Vehicle Charger',
  'ca840': 'Apple Lightning to USB Cable (2 m)',
  'cz550': 'ZAGG InvisibleShield Glass Screen Protector for Apple iPhone 8, iPhone 7/7S iPhone 6/6S',
  'ss25': 'Samsung 55” Class Curved 4K (2160P) Smart LED TV ',
  'ss45': 'Samsung 65" Class Curved 4K (2160P) Smart LED TV ',
  'sv33': 'VIZIO 48" Class FHD (1080P) Smart Full Array LED TV (D48-D0)',
  'ds03': 'Sharp Aquos Lc-70sq15u 70" 3d Ready 1080p Led-lcd Tv - 16:9 - Hdtv 1080p - 240 Hz - Atsc - 1920 X 1080',
  'hl54': 'LG Tone HBS-800 Ultra Bluetooth Stereo Headset, Assorted Colors',
  'gc40': 'CybertronPC Gaming Desktop Computer Rhodium (Black/Green)',
  'gr33': 'Refurbished Cyberpower Custom Gaming Desktop AMD Vishera FX-4300',
  'ad54': 'Dell Inspiron 3048 20" Touch All-in-One Desktop PC with Intel Pentium G3240T Processor',
  'im22': 'Microsoft Surface Pro 4',
  'id63': 'Dell - Inspiron 15 5000 2-in-1, 15.6-inch FHD, Intel Core i7-7500U, 8GB ',
  'td54': 'Dell - Inspiron11.6" Touch-Screen Laptop - Intel Pentium',
  'kl49': 'Logitech K360 Wireless Keyboard for Windows, Black',
  'kl87': 'Logitech Corded Mouse M100',
  'uv32': 'Verbatim 4GB USB 2.0 Flash Drive, Blue',
  'wr95': 'ROCKSOUL 1080P HD Webcam, White',
  'wv74': 'V7 CS0300-1N Vantage Webcam 300k',
  'wg30': 'Gear Head 8MP 1080p Webcam',
  'wg58': 'GoPro HERO6 Black Camera',
  'bc68': 'Case Logic DCB-304 Compact System/Hybrid Camera Case (Black)',
  'bc78': 'Camera Bag Camera Backpack By G-raphy for DSLR Cameras , Mirrorless Cameras',
  'qa90': 'Apple iPad mini 4 (128GB, Wi-Fi, Space Gray)',
  'qr63': 'RCA Cambio 10.1" 2-in-1 Tablet 32GB Intel Quad Core Windows 10',
  'dm75': 'Microsoft Surface Pro 1 Tablet 128 GB Dual-Core i5 ',
  'dd35': 'Dell Venue 8 Pro 3000 Series 32GB Windows Tablet with Intel 1.83 GHz Processor(Certified Refurbished)',
  'cb47': 'Apple iPad 4, iPad 3 & iPad 2 Keyboard Case(Black)'}
  export const reverseItemLabels = createReverseMapping(itemLabel);
  export const reverseItemTypeLabels = createReverseMapping(itemTypeLabel);
  export const reverseSubclassLabels = createReverseMapping(subclassLabel);
  export const reverseClassLabels = createReverseMapping(classLabel);
  export const reverseDepartmentLabels = createReverseMapping(departmentLabel);
  export const reverseDivisionLabels = createReverseMapping(divisionLabel);
  export const reverseCompanyLabels = createReverseMapping(companyLabel);
  export const reverseRegionLabels = createReverseMapping(regionLabel);
  export const reverseChannelLabels = createReverseMapping(channelLabel);
  export const reverseStoreLabels = createReverseMapping(storeLabel);
  export const reverseskuLabels = createReverseMapping(skuLabel);