version: '3.8'

services:
  front:
    build: ./pfeFront/
    # Add your front-end container configuration here
    ports:
      - "3000:3000"

  cassandra1: 
 
    image: cassandra:latest 
    healthcheck:
      test: ["CMD", "cqlsh","-e","DESCRIBE KEYSPACES"]
      interval: 100s
      timeout: 100s 
 
    container_name: cassandra1 
 
    hostname: cassandra1 
 
    networks: 
 
      - my-network
 
    ports: 
 
      - "9042:9042" 
 
    environment: &environment  
 
        CASSANDRA_SEEDS: "cassandra1,cassandra2"   
 
        CASSANDRA_CLUSTER_NAME: ChallengeCluster 
 
        CASSANDRA_DC: datacenter1
 
        CASSANDRA_RACK: RACK1 
 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
 

 
  cassandra2: 

    
    image: cassandra:latest 
    healthcheck:
      test: ["CMD", "cqlsh","-e","DESCRIBE KEYSPACES"]
      interval: 100s
      timeout: 100s 
 
    container_name: cassandra2 
 
    hostname: cassandra2 
 
    networks: 
 
      - my-network
 
    ports: 
 
      - "9044:9042" 
 
    environment: *environment   
 
    depends_on: 
 
      cassandra1:   
 
        condition: service_healthy 
  back_image:
    build: ./pfeBack/
    stdin_open: true
    tty: true
    environment:
      - CASSANDRA_ENDPOINT=cassandra1
    # Add your back-end container configuration here
    depends_on:
      cassandra2:
        condition: service_healthy
      cassandra1:
        condition: service_healthy
    networks:
      - my-network
    ports:
      - "8080:8080"

networks:
  my-network:
    driver: bridge
