kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 45451
nodes:
  - role: control-plane
    labels:
      nodelabel: control-node
  - role: worker
    labels:
      nodelabel: node-1
  - role: worker
    labels:
      nodelabel: node-2
